# Generated by Django 3.0.7 on 2020-06-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
